const api = window.medicineDesktop;
const $ = id => document.getElementById(id);
const loginModal = $('loginModal'), adminModal = $('adminModal'), appShell = $('appShell');
let currentUser = null;
let profiles = [];
let currentCategory = 'Medicine';

const medicineItems = [['Tylocin',3436],['Neodox',573],['vimeral',988],['Groviplex',570],['E-Sol',511],['Nutrigrow',802],['Amnovel',725],['Amprolium',1250],['Meriflox',1080],['Fit-5',700],['Tetracycline',58],['Success',52],['Brotane',1340],['Bayrocin',3444],['U.T.Mint',1200],['Chicktonite',675],['VEGUT',830],['Hapeto Care',1068],['Milliunum',360],['ESB3',382],['Protexin',182],['Trapin',130],['Futres-c',210],['Gpromine',1250],['Caritrol',2071],['Harbalc',805],['Liuoliv',304],['Liuotox',802]].map(([name,rate])=>({name,rate}));
const vaccineItems = [['F1 - 500',26],['F1 - 1000',52],['F1 - 2000',104],['B₂K - 500',147],['B₂K - 1000',294],['B₂K - 2000',588],['Lasota - 500',26],['Lasota - 1000',52],['Lasota - 2000',104]].map(([name,rate])=>({name,rate}));
const disinfectItems = [['Korsholine',5706],['Sokrena',3616],['H-plus',932],['Valkun',1100]].map(([name,rate])=>({name,rate}));

function toast(message){$('toast').textContent=message;$('toast').className='toast show';setTimeout(()=>$('toast').className='toast',2500)}
function setLoggedIn(user){currentUser=user;$('loggedInAs').textContent=`Signed in: ${user.username}`;$('adminButton').style.display=user.role==='admin'?'inline-block':'none';loginModal.classList.add('hidden');appShell.style.display='block';loadProfiles();}
async function login(){const r=await api.login($('loginUser').value,$('loginPassword').value);if(!r.ok){$('loginMessage').textContent=r.message;return}setLoggedIn(r)}
function logout(){currentUser=null;appShell.style.display='none';loginModal.classList.remove('hidden');$('loginPassword').value='';}
function loadProfiles(){api.listRecords().then(records=>{profiles=[...new Set(records.map(r=>r.customerName).filter(Boolean))];updateDropdown();});}
function updateDropdown(){const d=$('nameDropdown');d.innerHTML='<option value="">Select a saved name</option>';profiles.forEach(p=>{const o=document.createElement('option');o.value=p;o.textContent=p;d.appendChild(o)});}
function saveName(){const name=$('nameInput').value.trim();if(!name)return toast('Enter a name first.');if(!profiles.includes(name))profiles.push(name);updateDropdown();$('nameDropdown').value=name;$('nameInput').value='';toast(`Name "${name}" is ready to use.`)}
async function deleteName(){const name=$('nameDropdown').value;if(!name)return toast('Select a name first.');if(!confirm(`Delete all saved records for "${name}"?`))return;const records=await api.listRecords();for(const r of records.filter(x=>x.customerName===name))await api.deleteRecord(r.fileName);profiles=profiles.filter(x=>x!==name);updateDropdown();toast('Name and its saved records deleted.')}
function addRow(name='',rate=0,quantity=0){const row=document.createElement('tr');row.innerHTML=`<td><input class="itemName" value="${escapeHtml(name)}"></td><td><input class="rate" type="number" step="0.01" value="${rate}"></td><td><input class="quantity" type="number" step="1" value="${quantity}"></td><td class="amount">0.00</td>`;$('stockTable').querySelector('tbody').appendChild(row)}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function initialize(items){const body=$('stockTable').querySelector('tbody');body.innerHTML='';items.forEach(i=>addRow(i.name,i.rate,0));$('pageTitle').textContent=`Details of ${currentCategory}`;$('totalLabel').style.display='none';$('totalLabel').textContent='';}
function setCategory(category){currentCategory=category;if(category==='Medicine')initialize(medicineItems);if(category==='Vaccination')initialize(vaccineItems);if(category==='Disinfect')initialize(disinfectItems)}
function calculate(){let total=0;document.querySelectorAll('#stockTable tbody tr').forEach(row=>{const rate=Number(row.querySelector('.rate').value)||0;const qty=Number(row.querySelector('.quantity').value)||0;const amount=rate*qty;row.querySelector('.amount').textContent=amount.toFixed(2);total+=amount});$('totalLabel').textContent=`Total: ${total.toFixed(2)}`;$('totalLabel').style.display='block';return total}
function addItem(){const name=prompt('Enter item name:');if(!name)return;const rate=Number(prompt('Enter item rate:')||0);if(Number.isNaN(rate))return toast('Invalid rate.');addRow(name,rate,1)}
async function saveRecord(){const customerName=$('nameDropdown').value||$('nameInput').value.trim();if(!customerName)return toast('Select or enter a name before saving.');const rows=[...document.querySelectorAll('#stockTable tbody tr')].map(row=>({name:row.querySelector('.itemName').value,rate:Number(row.querySelector('.rate').value)||0,quantity:Number(row.querySelector('.quantity').value)||0,amount:Number(row.querySelector('.amount').textContent)||0}));const total=calculate();const record={user:currentUser.username,customerName,batchNumber:$('batchNumberInput').value.trim(),date:$('datePicker').value,category:currentCategory,items:rows,total};const result=await api.saveRecord(record);if(result.ok){if(!profiles.includes(customerName)){profiles.push(customerName);updateDropdown()}toast(`Record saved to C:\\medicine data`)}else toast('Could not save record.')}

function ensureRecordViewer(){if($('recordViewerModal'))return;const modal=document.createElement('div');modal.id='recordViewerModal';modal.className='modal hidden';modal.innerHTML=`<div class="card" style="width:min(1100px,94vw)"><h2 id="viewTitle">Saved Record</h2><div id="viewMeta" class="muted"></div><div class="table-wrap"><table id="viewTable"><thead><tr><th>Item Name</th><th>Rate</th><th>Quantity</th><th>Amount</th></tr></thead><tbody></tbody></table></div><div id="viewTotal" style="font-weight:bold;text-align:right;margin-top:12px"></div><div style="margin-top:18px;text-align:right"><button id="viewPrintButton" class="success">Print Record</button> <button id="closeViewerButton">Close</button></div></div>`;document.body.appendChild(modal);$('closeViewerButton').addEventListener('click',()=>modal.classList.add('hidden'));$('viewPrintButton').addEventListener('click',printViewedRecord)}
let viewedRecord=null;
function showRecord(record){ensureRecordViewer();viewedRecord=record;$('viewTitle').textContent=`${record.category||'Record'} — ${record.customerName||'Unnamed'}`;$('viewMeta').textContent=`User: ${record.user||''} | Batch: ${record.batchNumber||'—'} | Date: ${record.date||'—'} | Saved: ${record.savedAt||'—'}`;$('viewTable').querySelector('tbody').innerHTML=(record.items||[]).map(i=>`<tr><td>${escapeHtml(i.name||'')}</td><td>${Number(i.rate||0).toFixed(2)}</td><td>${Number(i.quantity||0)}</td><td>${Number(i.amount||0).toFixed(2)}</td></tr>`).join('');$('viewTotal').textContent=`Total: ${Number(record.total||0).toFixed(2)}`;$('recordViewerModal').classList.remove('hidden')}
function printViewedRecord(){if(!viewedRecord)return;const w=window.open('','_blank','width=1000,height=800');if(!w)return toast('Please allow pop-ups to print the record.');const r=viewedRecord;const rows=(r.items||[]).map(i=>`<tr><td>${escapeHtml(i.name||'')}</td><td>${Number(i.rate||0).toFixed(2)}</td><td>${Number(i.quantity||0)}</td><td>${Number(i.amount||0).toFixed(2)}</td></tr>`).join('');w.document.write(`<!doctype html><html><head><title>Medicine Record</title><style>body{font-family:Arial;padding:30px;color:#222}h1{margin-bottom:8px}p{margin:5px 0;color:#555}table{width:100%;border-collapse:collapse;margin-top:25px}th,td{border:1px solid #ccc;padding:9px;text-align:center}th{background:#f4f4f4}.total{text-align:right;font-size:18px;font-weight:bold;margin-top:15px}</style></head><body><h1>Medicine Details Manager</h1><h2>${escapeHtml(r.category||'Record')} — ${escapeHtml(r.customerName||'Unnamed')}</h2><p>User: ${escapeHtml(r.user||'')}</p><p>Batch: ${escapeHtml(r.batchNumber||'—')} &nbsp; Date: ${escapeHtml(r.date||'—')} &nbsp; Saved: ${escapeHtml(r.savedAt||'—')}</p><table><thead><tr><th>Item Name</th><th>Rate</th><th>Quantity</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table><div class="total">Total: ${Number(r.total||0).toFixed(2)}</div><script>window.onload=()=>window.print();<\/script></body></html>`);w.document.close()}

async function openAdmin(){if(!currentUser||currentUser.role!=='admin')return;adminModal.classList.remove('hidden');const users=await api.listUsers();$('usersList').innerHTML=users.map(u=>`<div class="record"><b>${escapeHtml(u.username)}</b> — ${u.role}${u.role!=='admin'?` <button onclick="resetPassword('${escapeHtml(u.username)}')">Reset Password</button>`:''}</div>`).join('');const records=await api.listRecords();$('recordsList').innerHTML=records.length?records.map((r,i)=>`<div class="record"><b>${escapeHtml(r.customerName||'Unnamed')}</b> — ${escapeHtml(r.category||'')} — ${escapeHtml(r.user||'')} — ${escapeHtml(r.date||'')} — Total ${Number(r.total||0).toFixed(2)}<br><span class="muted">Batch: ${escapeHtml(r.batchNumber||'')} | Saved: ${escapeHtml(r.savedAt||'')}</span><div style="margin-top:8px"><button onclick="viewAdminRecord(${i})">View</button> <button onclick="printAdminRecord(${i})" class="success">Print</button> <button onclick="deleteAdminRecord('${escapeHtml(r.fileName)}')" class="danger">Delete</button></div></div>`).join(''):'<p class="muted">No saved records yet.</p>';window.adminRecords=records}
function viewAdminRecord(index){const r=(window.adminRecords||[])[index];if(r)showRecord(r)}
function printAdminRecord(index){const r=(window.adminRecords||[])[index];if(r){showRecord(r);setTimeout(printViewedRecord,100)}}
async function createUser(){const r=await api.createUser($('newUser').value,$('newPassword').value);if(!r.ok)return toast(r.message);$('newUser').value='';$('newPassword').value='';toast('User created.');openAdmin()}
async function resetPassword(username){const password=prompt(`New password for ${username}:`);if(!password)return;const r=await api.resetPassword(username,password);toast(r.ok?'Password reset.':r.message)}
async function deleteAdminRecord(fileName){if(!confirm('Delete this saved record?'))return;await api.deleteRecord(fileName);openAdmin()}
$('loginButton').addEventListener('click',login);$('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('logoutButton').addEventListener('click',logout);$('saveButton').addEventListener('click',saveName);$('deleteButton').addEventListener('click',deleteName);$('medicine').addEventListener('click',()=>setCategory('Medicine'));$('vaccination').addEventListener('click',()=>setCategory('Vaccination'));$('disinfect').addEventListener('click',()=>setCategory('Disinfect'));$('addItemButton').addEventListener('click',addItem);$('calculateButton').addEventListener('click',calculate);$('saveRecordButton').addEventListener('click',saveRecord);$('printButton').addEventListener('click',()=>window.print());$('adminButton').addEventListener('click',openAdmin);$('closeAdminButton').addEventListener('click',()=>adminModal.classList.add('hidden'));$('createUserButton').addEventListener('click',createUser);
setCategory('Medicine');
api.getDataFolder().then(folder=>console.log('Local data folder:',folder));
